### PR TITLE
Fixes #123 cell::value / format when copying between different workbooks

### LINKED ISSUE #123: void cell::value(const cell c) don't check if the arg cell is from the same workbook
**Summary**

`xlnt::cell::value(const cell)` works when both cells belong to the same workbook, but breaks when copying a `shared_string` cell from one workbook to another.

**Expected vs actual**

* **Expected:** `cell::value(const cell)` should either:

  * be safe to use across workbooks (remapping shared strings into the destination workbook), or
  * clearly reject / assert when the argument cell belongs to a different workbook.

* **Actual:** it silently copies the internal shared string index, which produces wrong strings (or invalid data) when the workbooks differ.

cellWorkBookA.value(cellWorkbookB);

```cpp
void cell::value(const cell c)
{
// There is no ownership checks

    d_->type_ = c.d_->type_;
    d_->value_numeric_ = c.d_->value_numeric_; // <---------- this is a reference of a string when it is a shared_string type
    d_->value_text_ = c.d_->value_text_;
    d_->hyperlink_ = c.d_->hyperlink_;
    d_->formula_ = c.d_->formula_;
    d_->format_ = c.d_->format_;
}

/// -------------

template <>
rich_text cell::value() const
{
    if (data_type() == cell::type::shared_string)
    {
        return workbook().shared_strings(static_cast<std::size_t>(d_->value_numeric_));  /// when it is a shared string, it searches in the current workbook and not the other woorkbook
    }

    return d_->value_text_;
}
```

My suggestion would be to:
1. Check the ownership
2. If it is another workbook, search/update the current shared_strings and fix the reference

**Workaround**

Until this is fixed, copying between different workbooks is safe if done via the public API, for example:

```cpp
dst_cell.value(src_cell.to_string());
// or, if you want to preserve rich text:
dst_cell.value(src_cell.value<xlnt::rich_text>());
```

### PR DESCRIPTION
**Pull request by Fabio3rs**
## Summary
This PR makes `xlnt::cell` safer and more robust when copying values and formats between different workbooks.

- `cell::value(const cell)` now detects cross-workbook copies and:
  - Remaps shared_string values into the destination workbook’s shared string table.
  - Copies formulas as text.
  - **Copies external hyperlinks**; internal hyperlinks (cell/range references) are not yet implemented.
  - Deep-copies the source cell format into the destination workbook.
- `cell::format(const format)` now:
  - Checks if the format belongs to the current workbook.
  - If not, clones all format properties into this workbook’s stylesheet using only the public API, avoiding foreign pointers.
  - Associates the style by name if present; **deep-cloning of style content is not yet implemented** (documented as a temporary limitation).
  - Within the same workbook, behavior remains unchanged (fast shallow copy).

## Implementation
- Added `cell::copy_from_other_workbook` and `cell::copy_format_from_other_workbook` helpers.
- Moved `workbook::owns_format(const format &)` to private (internal use only).
- Added `workbook::clone_format_from(const format &)` to centralize format deep-copy logic on the workbook since the create format/stylesheet is ownership of the workbook.
- Updated documentation to clarify hyperlink and style copy limitations.
- Added and improved tests:
  - `test_copy_value_between_workbooks`
  - `test_format_from_different_workbook`
  - Tests use scope destruction to prove deep-copy and avoid fragile pointer dependencies.
  - Format tests were simplified to check only essential properties and behaviors.

## Note

I’m new to the xlnt codebase, so I’m happy to adjust the design, naming, or behavior to better match existing conventions.

### CODE REVIEW

**Comment by m7913d** [comment]
Coverage report is available at: [full](https://xlnt-community.github.io/xlnt-coverage/2ed05f22646680ad1ef1cd79135367baad9c9402/differential/index.html) | [review summary](https://xlnt-community.github.io/xlnt-coverage/2ed05f22646680ad1ef1cd79135367baad9c9402/review/index.html)

**Comment by m7913d** [comment]
Coverage report is available at: [full](https://xlnt-community.github.io/xlnt-coverage/3371db778c75b99d3eda04fe49d5e6f3c0ca7e7d/differential/index.html) | [review summary](https://xlnt-community.github.io/xlnt-coverage/3371db778c75b99d3eda04fe49d5e6f3c0ca7e7d/review/index.html)

File: include/xlnt/workbook/workbook.hpp [hunk 1]
```diff
@@ -803,6 +803,12 @@ class XLNT_API workbook
     /// </summary>
     xlnt::format create_format(bool default_format = false);
 
+    /// <summary>
+    /// Returns true if the given format belongs to this workbook's stylesheet.
+    /// Used to detect cross-workbook format references that could cause dangling pointers.
+    /// </summary>
+    bool owns_format(const class format &fmt) const;
```
Comment (m7913d) [inline include/xlnt/workbook/workbook.hpp]: Is this something that should be part of our public interface or is this rather an implementation detail?

File: source/cell/cell.cpp [hunk 2]
```diff
@@ -276,6 +283,46 @@ void cell::value(const cell c)
...
 
+void cell::copy_from_other_workbook(const cell &source)
+{
+    d_->type_ = source.d_->type_;
+
+    // Handle shared_string: remap to destination workbook
+    if (source.data_type() == type::shared_string)
+    {
+        const auto text = source.value<rich_text>();
+        const auto new_index = workbook().add_shared_string(text, false);
```
Comment (m7913d) [inline source/cell/cell.cpp]: maybe we can just call `cell::value(const rich_text &text)` to avoid duplicating those internal details. Or implement it in a separate function if you want to avoid the unnecessary call to `check_string` (called by `cell::value(const rich_text &text)`)

File: source/cell/cell.cpp [hunk 3]
```diff
@@ -767,9 +814,115 @@ bool cell::has_format() const
...
+
+    // Same workbook: direct assignment (original behavior)
     d_->format_ = new_format.d_;
 }
 
+void cell::copy_format_from_other_workbook(const class format &source_format)
+{
+    // Option B: Automatically clone the format to this workbook's stylesheet
+    // Start with a blank format from our workbook
+    auto cloned_format = workbook().create_format(true);
```
Comment (m7913d) [inline source/cell/cell.cpp]: I don't think you want to change the default format here (i.e. pass true as first argument). This sets the default format of the workbook (although the concept of default format is not fully implemented in xlnt).

File: source/cell/cell.cpp [hunk 4]
```diff
@@ -767,9 +814,115 @@ bool cell::has_format() const
...
+    if (source_format.d_->alignment_id.is_set())
+    {
+        auto src_alignment = source_format.d_->parent->alignments.at(source_format.d_->alignment_id.get());
+        cloned_format.alignment(src_alignment, source_format.d_->alignment_applied);
+    }
+
+    // Copy border if present
+    if (source_format.d_->border_id.is_set())
+    {
+        auto src_border = source_format.d_->parent->borders.at(source_format.d_->border_id.get());
```
Comment (m7913d) [inline source/cell/cell.cpp]: idem

File: source/cell/cell.cpp [hunk 5]
```diff
@@ -767,9 +814,115 @@ bool cell::has_format() const
...
+        cloned_format.border(src_border, source_format.d_->border_applied);
+    }
+
+    // Copy fill if present
+    if (source_format.d_->fill_id.is_set())
+    {
+        auto src_fill = source_format.d_->parent->fills.at(source_format.d_->fill_id.get());
```
Comment (m7913d) [inline source/cell/cell.cpp]: idem

File: source/cell/cell.cpp [hunk 6]
```diff
@@ -767,9 +814,115 @@ bool cell::has_format() const
...
+        cloned_format.fill(src_fill, source_format.d_->fill_applied);
+    }
+
+    // Copy font if present
+    if (source_format.d_->font_id.is_set())
+    {
+        auto src_font = source_format.d_->parent->fonts.at(source_format.d_->font_id.get());
```
Comment (m7913d) [inline source/cell/cell.cpp]: idem

File: source/cell/cell.cpp [hunk 7]
```diff
@@ -767,9 +814,115 @@ bool cell::has_format() const
...
+        cloned_format.font(src_font, source_format.d_->font_applied);
+    }
+
+    // Copy number format if present
+    if (source_format.d_->number_format_id.is_set())
+    {
+        const auto number_format_id = source_format.d_->number_format_id.get();
```
Comment (m7913d) [inline source/cell/cell.cpp]: Can't we avoid this code duplication by just calling `source_format.number_format()`?

File: source/cell/cell.cpp [hunk 8]
```diff
@@ -767,9 +814,115 @@ bool cell::has_format() const
...
+            }
+        }
+
+        cloned_format.number_format(src_number_format, source_format.d_->number_format_applied);
+    }
+
+    // Copy protection if present
+    if (source_format.d_->protection_id.is_set())
+    {
+        auto src_protection = source_format.d_->parent->protections.at(source_format.d_->protection_id.get());
```
Comment (m7913d) [inline source/cell/cell.cpp]: idem

File: source/cell/cell.cpp [hunk 9]
```diff
@@ -767,9 +814,115 @@ bool cell::has_format() const
...
+        cloned_format.protection(src_protection, source_format.d_->protection_applied);
+    }
+
+    // Copy other properties
+    if (source_format.d_->pivot_button_)
```
Comment (m7913d) [inline source/cell/cell.cpp]: This test is not really needed. We can just call `pivot_button`. Advantage is that we do not depend on the default value of `pivot_button_`

File: source/cell/cell.cpp [hunk 10]
```diff
@@ -767,9 +814,115 @@ bool cell::has_format() const
...
+
+    // Try to copy style name if it exists in destination workbook
+    // This preserves style-based formatting when styles are shared across workbooks
+    if (source_format.d_->style.is_set())
+    {
+        const auto &style_name = source_format.d_->style.get();
+
+        // Only copy if destination workbook has a style with the same name
+        // This avoids creating style name mismatches or conflicts
+        if (workbook().has_style(style_name))
```
Comment (m7913d) [inline source/cell/cell.cpp]: Better (?) alternative would be perform a deep copy of the style too, if the target workbook doesn't contain the style.
Even if the target workbook contains a style with the given name, one could argue that we should still perform a deep copy of the style if the style with this name doesn't match in the source and target workbook.
Nevertheless, I'm ok with how it is currently implemented for now. I would just document the current behaviour and mention that deep cloning of the style is not yet implemented.

File: source/workbook/workbook.cpp [hunk 11]
```diff
@@ -1470,6 +1470,21 @@ format workbook::create_format(bool default_format)
...
 }
 
+bool workbook::owns_format(const class format &fmt) const
+{
+    if (!d_->stylesheet_.is_set())
+    {
+        return false;
+    }
+
+    if (!fmt.d_ || !fmt.d_->parent)
```
Comment (m7913d) [inline source/workbook/workbook.cpp]: Ok, but this check will never be true.

File: tests/cell/cell_test_suite.cpp [hunk 12]
```diff
@@ -849,6 +853,328 @@ class cell_test_suite : public test_suite
...
+        cell_b.value(cell_a);
+
+        // Verify string is preserved correctly
+        xlnt_assert_equals(cell_b.value<std::string>(), "Test String");
+        xlnt_assert(cell_b.data_type() == xlnt::cell::type::shared_string);
+
+        // Verify workbooks are different
+        auto workbook_a = cell_a.workbook();
+        auto workbook_b = cell_b.workbook();
+        xlnt_assert(&workbook_a != &workbook_b);
```
Comment (m7913d) [inline tests/cell/cell_test_suite.cpp]: I think this doesn't really test anything. As it compare the addresses of different local variables (not references). Those will be always different. I guess, you actually want to test `xlnt_assert(workbook_a != workbook_b);`; which tests whether they contain different internal pointers.

File: tests/cell/cell_test_suite.cpp [hunk 13]
```diff
@@ -849,6 +853,328 @@ class cell_test_suite : public test_suite
...
+        cell_a5.font(xlnt::font().bold(true));
+        xlnt_assert(cell_a5.has_format());
+
+        auto cell_b5 = ws_b.cell("B5");
+        cell_b5.value(cell_a5);
+        xlnt_assert_equals(cell_b5.value<std::string>(), "Formatted");
+        xlnt_assert(cell_b5.has_format()); // Format IS copied with automatic deep-copy
+        xlnt_assert(cell_b5.font().bold()); // And formatting properties are preserved
+
+        // Test that same-worksheet copy uses shallow copy (original behavior preserved)
```
Comment (m7913d) [inline tests/cell/cell_test_suite.cpp]: I think this test does not cleanly tests that a shallow copy if made. Also if a deep copy is made, all tests will succeed (except for the hyperlink). F.ex. checking whether the number of formats doesn't increase may more directly ensure a shallow copy is effectively made.

File: tests/cell/cell_test_suite.cpp [hunk 14]
```diff
@@ -849,6 +853,328 @@ class cell_test_suite : public test_suite
...
+
+        xlnt_assert(cell_b.has_format());
+        xlnt_assert(cell_b.font().bold());
+        xlnt_assert_equals(cell_b.font().size(), 14.0);
+
+        // Test 2: Multiple format properties are cloned
+        xlnt::workbook wb_c;
+        auto fmt_c = wb_c.create_format();
+        fmt_c.font(xlnt::font().italic(true), true);
+        fmt_c.number_format(xlnt::number_format::percentage(), true);
```
Comment (m7913d) [inline tests/cell/cell_test_suite.cpp]: you do not check whether the number format is correctly copied.

File: tests/cell/cell_test_suite.cpp [hunk 15]
```diff
@@ -849,6 +853,328 @@ class cell_test_suite : public test_suite
...
+
+        // Format count should NOT increase (shallow copy)
+        xlnt_assert_equals(wb_same.format_count(), initial_format_count);
+
+        // Both cells should share the same format object
+        xlnt_assert(cell_dest.has_format());
+        xlnt_assert_equals(cell_dest.font().bold(), true);
+        xlnt_assert_equals(cell_dest.font().size(), 14.0);
+
+        // Test 7: cell::value() clones format from different workbook (automatic deep-copy)
```
Comment (m7913d) [inline tests/cell/cell_test_suite.cpp]: Maybe we can also check whether the format count is indeed increased in the target workbook. This would cleanly indicate that the format is indeed deep copied into the new workbook.

File: include/xlnt/workbook/workbook.hpp (hunk 1 above)
Comment (Fabio3rs) [reply include/xlnt/workbook/workbook.hpp]: I was thinking it could be useful to the users, but I am thinking better and maybe we should make it private with friendship and only expose as public interface later if really needed.

File: source/cell/cell.cpp [hunk 16]
```diff
@@ -283,35 +282,48 @@ void cell::value(const cell c)
...
     // Handle shared_string: remap to destination workbook
     if (source.data_type() == type::shared_string)
     {
-        const auto text = source.value<rich_text>();
-        const auto new_index = workbook().add_shared_string(text, false);
-        d_->value_numeric_ = static_cast<double>(new_index);
-        d_->value_text_ = rich_text();
+        value_no_check(source.value<rich_text>());
     }
     else if (source.data_type() == type::inline_string || source.data_type() == type::formula_string)
```
Comment (m7913d) [inline source/cell/cell.cpp]: Maybe we can just skip this case.

File: tests/cell/cell_test_suite.cpp [hunk 17]
```diff
@@ -849,6 +853,171 @@ class cell_test_suite : public test_suite
...
+            // External hyperlink should be copied on cross-workbook copy
+            cell_source.hyperlink("https://example.com");
+
+            cell_dest.value(cell_source);
+        }
+        // Source workbook destroyed - if raw pointers were copied, this would crash/corrupt
+
+        xlnt_assert_equals(cell_dest.value<std::string>(), "Test String");
+        xlnt_assert(cell_dest.has_formula());
+        xlnt_assert(cell_dest.has_format());
```
[the remark this answers is not in the document]
Comment (Fabio3rs) [reply tests/cell/cell_test_suite.cpp]: Do you think I should use the .format() and check every method? The .font() check tests the changes I did on the scope (bold and size 14) (On the lines bellow)

**Comment by Fabio3rs** [comment]
> @Fabio3rs could you update your branch with our latest master branch and resolve conflicts if any?

Updated. Git updated without conflicts.

**Comment by m7913d** [comment]
Coverage report is available at: [full](https://xlnt-community.github.io/xlnt-coverage/c9d0ff0b8ecbd7422e3578f6cd919c888a0efd98/differential/index.html) | [review summary](https://xlnt-community.github.io/xlnt-coverage/c9d0ff0b8ecbd7422e3578f6cd919c888a0efd98/review/index.html)

**Comment by m7913d** [comment]
@Fabio3rs Thanks for your PR and all the changes!
